// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace FoxxyTestMod
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "FoxxyTestMod";
        public const string Version     = "0.1.0";
        public const string Title       = "Foxxy's Test Mod";
        public const string Description = "Foxxy's Testing Mod, not for regular use";
    }
}
